# Generated by Django 3.0.2 on 2020-01-10 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140, verbose_name='カテゴリ名')),
                ('description', models.CharField(blank=True, max_length=140, null=True, verbose_name='説明')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=140, verbose_name='タイトル')),
                ('text', models.TextField(verbose_name='本文')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('published_at', models.DateTimeField(verbose_name='投稿日時')),
                ('updated_at', models.DateTimeField(verbose_name='更新日時')),
                ('category', models.ManyToManyField(to='blogs.Category', verbose_name='カテゴリ')),
            ],
        ),
    ]
