# Generated by Django 3.0.2 on 2020-01-10 05:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_auto_20200110_1419'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='blogs.User', verbose_name='執筆者'),
            preserve_default=False,
        ),
    ]
