# Generated by Django 3.0.2 on 2020-01-10 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0006_auto_20200110_1616'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='comment',
        ),
        migrations.AddField(
            model_name='post',
            name='comment',
            field=models.ManyToManyField(blank=True, null=True, to='blogs.Comment', verbose_name='コメント'),
        ),
    ]
