# Generated by Django 3.0.2 on 2020-01-10 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0009_auto_20200110_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(default='未分類', max_length=255, verbose_name='カテゴリ名'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='title',
            field=models.CharField(max_length=255, verbose_name='コメントタイトル'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='username',
            field=models.CharField(max_length=255, verbose_name='ニックネーム'),
        ),
        migrations.AlterField(
            model_name='image',
            name='name',
            field=models.CharField(max_length=255, verbose_name='ファイル名'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=255, verbose_name='タイトル'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=255, verbose_name='タグ名'),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(default='名無し', max_length=255, verbose_name='ユーザー名'),
        ),
    ]
